### ISSUE TITLE
ytel-show

### ISSUE THREAD

**Issue by xFA25E** [gRastello/ytel#16]
Hi, I have made a plugin package for ytel.

**Comment by xFA25E** [comment]
It's https://github.com/xFA25E/ytel-show . It is a video/comments show. It relies on ytel to fetch and draw information.
Do you thing it is a good idea to list it somewhere in a readme? Thanks

**Comment by spiderbit** [comment]
interesting I did that for comments:
(defun ytel-comment ()
    "Jump to comments."
    (interactive)
    (let* ((video (ytel-get-current-video))
	   (id    (ytel-video-id-fun video)))
      (browse-url (concat ytel-invidious-api-url "/watch?v=" id "#comments"))))

but your solution is interesting... currently no instance seem to work over the client, not sure what the problem is.
https://github.com/spiderbit/ytel/tree/tabulated-list

That's my fork but I was to lazy to merge it to master... any thoughts on that?

**Comment by gRastello** [comment]
> It's https://github.com/xFA25E/ytel-show . It is a video/comments shower. It relies on ytel to fetch and draw information.
> Do you thing it is a good idea to list it somewhere in a readme? Thanks

Yeah, I've added it to the README.
